name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Primary validation job - runs on every PR/push
  validate:
    runs-on: ubuntu-latest
    name: Code Validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Build project
        run: pnpm build

  # Cross-platform compatibility - only build validation
  cross-platform:
    strategy:
      matrix:
        os: [macos-latest] # Only test macOS since Ubuntu is covered in validate job
        node-version: ['22']

    runs-on: ${{ matrix.os }}
    name: Cross-platform (${{ matrix.os }})
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and validate
        run: pnpm build:validate
