name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Primary validation job - runs on every PR/push
  validate:
    runs-on: ubuntu-latest
    name: Code Validation
    outputs:
      should-run-full-tests: ${{ steps.check-labels.outputs.full-test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check

      - name: Run unit tests
        run: pnpm test

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Build project
        run: pnpm build

      - name: Check if full tests should run
        id: check-labels
        run: |
          if [[ "${{ github.event_name }}" == "push" ]] || [[ "${{ contains(github.event.pull_request.labels.*.name, 'full-test') }}" == "true" ]]; then
            echo "full-test=true" >> $GITHUB_OUTPUT
          else
            echo "full-test=false" >> $GITHUB_OUTPUT
          fi

  # Full server testing - only when needed
  server-tests:
    runs-on: ubuntu-latest
    name: Server Integration Tests
    needs: validate
    if: needs.validate.outputs.should-run-full-tests == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Run health check (one-shot)
        run: pnpm health:oneshot
        env:
          MASTRA_SERVERS: 'http://localhost:4111'

      - name: Run full checks (one-shot)
        run: pnpm check:oneshot
        env:
          MASTRA_SERVERS: 'http://localhost:4111'

  # Cross-platform compatibility - only build validation
  cross-platform:
    strategy:
      matrix:
        os: [macos-latest] # Only test macOS since Ubuntu is covered in validate job
        node-version: ['22']

    runs-on: ${{ matrix.os }}
    name: Cross-platform (${{ matrix.os }})
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and validate
        run: pnpm build:validate
